<?php
/**
 * Resume
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Авито API для бизнеса
 *
 * ## Общая информация Описание API произведено в формате [**Swagger 3.0**](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md). Вы можете использовать данный файл для ознакомления с методами API, а также для генерации базового кода для работы с API на удобном для вас языке программирования с помощью утилиты [**Swagger Codegen**](https://swagger.io/swagger-codegen/) или online сервиса [**Swagger Editor**](https://editor.swagger.io/).  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**  По всем вопросам работы с API необходимо обращаться в Службу Поддержки профессиональных инструментов:  <li>телефон: <b>+7 495 777-10-66</b></li> <li>email: <a href=\"mailto:supportautoload@avito.ru\">supportautoload@avito.ru</a></li>
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Resume Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Resume implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Resume';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
'title' => 'string',
'description' => 'string',
'url' => 'string',
'experience' => '\Swagger\Client\Model\Experience[]',
'education' => '\Swagger\Client\Model\Education[]',
'language' => '\Swagger\Client\Model\Language[]',
'location' => '\Swagger\Client\Model\Location',
'photos' => '\Swagger\Client\Model\Photo[]',
'specialization' => '\Swagger\Client\Model\Specialization',
'schedule' => '\Swagger\Client\Model\WorkSchedule',
'education_level' => '\Swagger\Client\Model\EducationLevel',
'gender' => '\Swagger\Client\Model\Gender',
'total_experience' => 'int',
'age' => 'int',
'citizenship' => '\Swagger\Client\Model\Citizenship',
'business_trip_readiness' => '\Swagger\Client\Model\BusinessTripReadiness',
'relocation_readiness' => '\Swagger\Client\Model\RelocationReadiness',
'salary' => 'float',
'is_purchased' => 'bool',
'created' => '\DateTime',
'updated' => '\DateTime'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int64',
'title' => null,
'description' => null,
'url' => null,
'experience' => null,
'education' => null,
'language' => null,
'location' => null,
'photos' => null,
'specialization' => null,
'schedule' => null,
'education_level' => null,
'gender' => null,
'total_experience' => 'int32',
'age' => 'int32',
'citizenship' => null,
'business_trip_readiness' => null,
'relocation_readiness' => null,
'salary' => 'float',
'is_purchased' => null,
'created' => 'date-time',
'updated' => 'date-time'    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
'title' => 'title',
'description' => 'description',
'url' => 'url',
'experience' => 'experience',
'education' => 'education',
'language' => 'language',
'location' => 'location',
'photos' => 'photos',
'specialization' => 'specialization',
'schedule' => 'schedule',
'education_level' => 'education_level',
'gender' => 'gender',
'total_experience' => 'total_experience',
'age' => 'age',
'citizenship' => 'citizenship',
'business_trip_readiness' => 'business_trip_readiness',
'relocation_readiness' => 'relocation_readiness',
'salary' => 'salary',
'is_purchased' => 'is_purchased',
'created' => 'created',
'updated' => 'updated'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
'title' => 'setTitle',
'description' => 'setDescription',
'url' => 'setUrl',
'experience' => 'setExperience',
'education' => 'setEducation',
'language' => 'setLanguage',
'location' => 'setLocation',
'photos' => 'setPhotos',
'specialization' => 'setSpecialization',
'schedule' => 'setSchedule',
'education_level' => 'setEducationLevel',
'gender' => 'setGender',
'total_experience' => 'setTotalExperience',
'age' => 'setAge',
'citizenship' => 'setCitizenship',
'business_trip_readiness' => 'setBusinessTripReadiness',
'relocation_readiness' => 'setRelocationReadiness',
'salary' => 'setSalary',
'is_purchased' => 'setIsPurchased',
'created' => 'setCreated',
'updated' => 'setUpdated'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
'title' => 'getTitle',
'description' => 'getDescription',
'url' => 'getUrl',
'experience' => 'getExperience',
'education' => 'getEducation',
'language' => 'getLanguage',
'location' => 'getLocation',
'photos' => 'getPhotos',
'specialization' => 'getSpecialization',
'schedule' => 'getSchedule',
'education_level' => 'getEducationLevel',
'gender' => 'getGender',
'total_experience' => 'getTotalExperience',
'age' => 'getAge',
'citizenship' => 'getCitizenship',
'business_trip_readiness' => 'getBusinessTripReadiness',
'relocation_readiness' => 'getRelocationReadiness',
'salary' => 'getSalary',
'is_purchased' => 'getIsPurchased',
'created' => 'getCreated',
'updated' => 'getUpdated'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['experience'] = isset($data['experience']) ? $data['experience'] : null;
        $this->container['education'] = isset($data['education']) ? $data['education'] : null;
        $this->container['language'] = isset($data['language']) ? $data['language'] : null;
        $this->container['location'] = isset($data['location']) ? $data['location'] : null;
        $this->container['photos'] = isset($data['photos']) ? $data['photos'] : null;
        $this->container['specialization'] = isset($data['specialization']) ? $data['specialization'] : null;
        $this->container['schedule'] = isset($data['schedule']) ? $data['schedule'] : null;
        $this->container['education_level'] = isset($data['education_level']) ? $data['education_level'] : null;
        $this->container['gender'] = isset($data['gender']) ? $data['gender'] : null;
        $this->container['total_experience'] = isset($data['total_experience']) ? $data['total_experience'] : null;
        $this->container['age'] = isset($data['age']) ? $data['age'] : null;
        $this->container['citizenship'] = isset($data['citizenship']) ? $data['citizenship'] : null;
        $this->container['business_trip_readiness'] = isset($data['business_trip_readiness']) ? $data['business_trip_readiness'] : null;
        $this->container['relocation_readiness'] = isset($data['relocation_readiness']) ? $data['relocation_readiness'] : null;
        $this->container['salary'] = isset($data['salary']) ? $data['salary'] : null;
        $this->container['is_purchased'] = isset($data['is_purchased']) ? $data['is_purchased'] : null;
        $this->container['created'] = isset($data['created']) ? $data['created'] : null;
        $this->container['updated'] = isset($data['updated']) ? $data['updated'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets experience
     *
     * @return \Swagger\Client\Model\Experience[]
     */
    public function getExperience()
    {
        return $this->container['experience'];
    }

    /**
     * Sets experience
     *
     * @param \Swagger\Client\Model\Experience[] $experience experience
     *
     * @return $this
     */
    public function setExperience($experience)
    {
        $this->container['experience'] = $experience;

        return $this;
    }

    /**
     * Gets education
     *
     * @return \Swagger\Client\Model\Education[]
     */
    public function getEducation()
    {
        return $this->container['education'];
    }

    /**
     * Sets education
     *
     * @param \Swagger\Client\Model\Education[] $education education
     *
     * @return $this
     */
    public function setEducation($education)
    {
        $this->container['education'] = $education;

        return $this;
    }

    /**
     * Gets language
     *
     * @return \Swagger\Client\Model\Language[]
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param \Swagger\Client\Model\Language[] $language language
     *
     * @return $this
     */
    public function setLanguage($language)
    {
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets location
     *
     * @return \Swagger\Client\Model\Location
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param \Swagger\Client\Model\Location $location location
     *
     * @return $this
     */
    public function setLocation($location)
    {
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets photos
     *
     * @return \Swagger\Client\Model\Photo[]
     */
    public function getPhotos()
    {
        return $this->container['photos'];
    }

    /**
     * Sets photos
     *
     * @param \Swagger\Client\Model\Photo[] $photos photos
     *
     * @return $this
     */
    public function setPhotos($photos)
    {
        $this->container['photos'] = $photos;

        return $this;
    }

    /**
     * Gets specialization
     *
     * @return \Swagger\Client\Model\Specialization
     */
    public function getSpecialization()
    {
        return $this->container['specialization'];
    }

    /**
     * Sets specialization
     *
     * @param \Swagger\Client\Model\Specialization $specialization specialization
     *
     * @return $this
     */
    public function setSpecialization($specialization)
    {
        $this->container['specialization'] = $specialization;

        return $this;
    }

    /**
     * Gets schedule
     *
     * @return \Swagger\Client\Model\WorkSchedule
     */
    public function getSchedule()
    {
        return $this->container['schedule'];
    }

    /**
     * Sets schedule
     *
     * @param \Swagger\Client\Model\WorkSchedule $schedule schedule
     *
     * @return $this
     */
    public function setSchedule($schedule)
    {
        $this->container['schedule'] = $schedule;

        return $this;
    }

    /**
     * Gets education_level
     *
     * @return \Swagger\Client\Model\EducationLevel
     */
    public function getEducationLevel()
    {
        return $this->container['education_level'];
    }

    /**
     * Sets education_level
     *
     * @param \Swagger\Client\Model\EducationLevel $education_level education_level
     *
     * @return $this
     */
    public function setEducationLevel($education_level)
    {
        $this->container['education_level'] = $education_level;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return \Swagger\Client\Model\Gender
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param \Swagger\Client\Model\Gender $gender gender
     *
     * @return $this
     */
    public function setGender($gender)
    {
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets total_experience
     *
     * @return int
     */
    public function getTotalExperience()
    {
        return $this->container['total_experience'];
    }

    /**
     * Sets total_experience
     *
     * @param int $total_experience total_experience
     *
     * @return $this
     */
    public function setTotalExperience($total_experience)
    {
        $this->container['total_experience'] = $total_experience;

        return $this;
    }

    /**
     * Gets age
     *
     * @return int
     */
    public function getAge()
    {
        return $this->container['age'];
    }

    /**
     * Sets age
     *
     * @param int $age age
     *
     * @return $this
     */
    public function setAge($age)
    {
        $this->container['age'] = $age;

        return $this;
    }

    /**
     * Gets citizenship
     *
     * @return \Swagger\Client\Model\Citizenship
     */
    public function getCitizenship()
    {
        return $this->container['citizenship'];
    }

    /**
     * Sets citizenship
     *
     * @param \Swagger\Client\Model\Citizenship $citizenship citizenship
     *
     * @return $this
     */
    public function setCitizenship($citizenship)
    {
        $this->container['citizenship'] = $citizenship;

        return $this;
    }

    /**
     * Gets business_trip_readiness
     *
     * @return \Swagger\Client\Model\BusinessTripReadiness
     */
    public function getBusinessTripReadiness()
    {
        return $this->container['business_trip_readiness'];
    }

    /**
     * Sets business_trip_readiness
     *
     * @param \Swagger\Client\Model\BusinessTripReadiness $business_trip_readiness business_trip_readiness
     *
     * @return $this
     */
    public function setBusinessTripReadiness($business_trip_readiness)
    {
        $this->container['business_trip_readiness'] = $business_trip_readiness;

        return $this;
    }

    /**
     * Gets relocation_readiness
     *
     * @return \Swagger\Client\Model\RelocationReadiness
     */
    public function getRelocationReadiness()
    {
        return $this->container['relocation_readiness'];
    }

    /**
     * Sets relocation_readiness
     *
     * @param \Swagger\Client\Model\RelocationReadiness $relocation_readiness relocation_readiness
     *
     * @return $this
     */
    public function setRelocationReadiness($relocation_readiness)
    {
        $this->container['relocation_readiness'] = $relocation_readiness;

        return $this;
    }

    /**
     * Gets salary
     *
     * @return float
     */
    public function getSalary()
    {
        return $this->container['salary'];
    }

    /**
     * Sets salary
     *
     * @param float $salary salary
     *
     * @return $this
     */
    public function setSalary($salary)
    {
        $this->container['salary'] = $salary;

        return $this;
    }

    /**
     * Gets is_purchased
     *
     * @return bool
     */
    public function getIsPurchased()
    {
        return $this->container['is_purchased'];
    }

    /**
     * Sets is_purchased
     *
     * @param bool $is_purchased is_purchased
     *
     * @return $this
     */
    public function setIsPurchased($is_purchased)
    {
        $this->container['is_purchased'] = $is_purchased;

        return $this;
    }

    /**
     * Gets created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime $created created
     *
     * @return $this
     */
    public function setCreated($created)
    {
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets updated
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->container['updated'];
    }

    /**
     * Sets updated
     *
     * @param \DateTime $updated updated
     *
     * @return $this
     */
    public function setUpdated($updated)
    {
        $this->container['updated'] = $updated;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
