<?php
/**
 * EventsAutotekaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Авито API для бизнеса
 *
 * ## Общая информация Описание API произведено в формате [**Swagger 3.0**](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md). Вы можете использовать данный файл для ознакомления с методами API, а также для генерации базового кода для работы с API на удобном для вас языке программирования с помощью утилиты [**Swagger Codegen**](https://swagger.io/swagger-codegen/) или online сервиса [**Swagger Editor**](https://editor.swagger.io/).  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**  По всем вопросам работы с API необходимо обращаться в Службу Поддержки профессиональных инструментов:  <li>телефон: <b>+7 495 777-10-66</b></li> <li>email: <a href=\"mailto:supportautoload@avito.ru\">supportautoload@avito.ru</a></li>
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EventsAutotekaTest Class Doc Comment
 *
 * @category    Class
 * @description Блок с предупреждениями об авто
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EventsAutotekaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EventsAutoteka"
     */
    public function testEventsAutoteka()
    {
    }

    /**
     * Test attribute "avito_on_sale"
     */
    public function testPropertyAvitoOnSale()
    {
    }

    /**
     * Test attribute "body_repair"
     */
    public function testPropertyBodyRepair()
    {
    }

    /**
     * Test attribute "crashes"
     */
    public function testPropertyCrashes()
    {
    }

    /**
     * Test attribute "dealer_data_available"
     */
    public function testPropertyDealerDataAvailable()
    {
    }

    /**
     * Test attribute "last_mileage_record"
     */
    public function testPropertyLastMileageRecord()
    {
    }

    /**
     * Test attribute "owners"
     */
    public function testPropertyOwners()
    {
    }

    /**
     * Test attribute "pledge"
     */
    public function testPropertyPledge()
    {
    }

    /**
     * Test attribute "public_person"
     */
    public function testPropertyPublicPerson()
    {
    }
}
