<?php
/**
 * ReportCollectionAutoloadInnerStatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Авито API для бизнеса
 *
 * ## Общая информация Описание API произведено в формате [**Swagger 3.0**](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md). Вы можете использовать данный файл для ознакомления с методами API, а также для генерации базового кода для работы с API на удобном для вас языке программирования с помощью утилиты [**Swagger Codegen**](https://swagger.io/swagger-codegen/) или online сервиса [**Swagger Editor**](https://editor.swagger.io/).  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**  По всем вопросам работы с API необходимо обращаться в Службу Поддержки профессиональных инструментов:  <li>телефон: <b>+7 495 777-10-66</b></li> <li>email: <a href=\"mailto:supportautoload@avito.ru\">supportautoload@avito.ru</a></li>
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReportCollectionAutoloadInnerStatTest Class Doc Comment
 *
 * @category    Class
 * @description Суммарная статистика по объявлению в данном отчете
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReportCollectionAutoloadInnerStatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReportCollectionAutoloadInnerStat"
     */
    public function testReportCollectionAutoloadInnerStat()
    {
    }

    /**
     * Test attribute "vas"
     */
    public function testPropertyVas()
    {
    }

    /**
     * Test attribute "success"
     */
    public function testPropertySuccess()
    {
    }

    /**
     * Test attribute "error_fee"
     */
    public function testPropertyErrorFee()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "unknown"
     */
    public function testPropertyUnknown()
    {
    }

    /**
     * Test attribute "stopped"
     */
    public function testPropertyStopped()
    {
    }

    /**
     * Test attribute "published"
     */
    public function testPropertyPublished()
    {
    }

    /**
     * Test attribute "fees"
     */
    public function testPropertyFees()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "problem"
     */
    public function testPropertyProblem()
    {
    }

    /**
     * Test attribute "problem_obsolete"
     */
    public function testPropertyProblemObsolete()
    {
    }

    /**
     * Test attribute "duplicate"
     */
    public function testPropertyDuplicate()
    {
    }

    /**
     * Test attribute "publish_later"
     */
    public function testPropertyPublishLater()
    {
    }
}
